services:
  postgres:
    image: postgres:latest
    container_name: bank_app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  bank_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local